apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8500
    targetPort: 8500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: faviog2/futurebank_back:0.1.0
        env:
        - name: DB_USER
          value: appuser
        - name: DB_PASSWORD
          value: myapppass
        - name: DB_CONNECT_STRING
          value: database-service:1521/xepdb1 
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m" # 1/10
        ports:
        - containerPort: 3800